version: "3"
services:
  nginx:
    image: nginx:1.14.0
    ports:
    - "8000:80"
    volumes:
    - ./web:/var/www/html:cached
    - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
  php:
    image: php:7.2-fpm
    build:
      context: ./docker/builds/php
    volumes:
      - ./web:/var/www/html:cached
      - ./docker/conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./scripts/drush.phar:/usr/local/bin/drush
      - ./scripts/composer.phar:/usr/local/bin/composer
    networks:
      - web
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/db:/var/lib/mysql
      # - ./data/db-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: drop
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drop
      MYSQL_PASSWORD: drop
    networks:
      - web
  mailhog:
    image: mailhog/mailhog
    hostname: mailhog
    ports:
      - "8025:8025"
      - "1025"
    networks:
      - web
networks:
  web:
    driver: bridge