version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
    - "8000:80"
    volumes:
    - ./web:/var/www/html:cached
    - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
  php:
    image: php:${PHP_VERSION}-fpm
    build: ./builds/php
    volumes:
      - ./web:/var/www/html:cached
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - web
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - web
  mailhog:
    image: mailhog/mailhog
    hostname: mailhog
    ports:
      - "8025:8025"
      - "1025"
    networks:
      - web
networks:
  web:
    driver: bridge