version: "3"

services:

  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
    - "8080:80"
    volumes:
    - ./web:/var/www/html:cached
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

  php:
    image: php:${PHP_VERSION}-fpm
    build: ./php
    volumes:
      - ./web:/var/www/html:cached
    networks:
      - web

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - web

networks:
  web:
    driver: bridge